name: metaphlan_metaphlan
description: MetaPhlAn taxonomic profiling (module vendored)
keywords:
  - metagenomics
  - taxonomy
tools:
  - metaphlan:
      description: MetaPhlAn metagenomic taxonomic profiler
      homepage: https://huttenhower.sph.harvard.edu/metaphlan/
      documentation: https://github.com/biobakery/MetaPhlAn
      tool_dev_url: https://github.com/biobakery/MetaPhlAn
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: Groovy map containing sample information
  - input:
      type: file
      description: FASTQ/FASTA/Bowtie2out/SAM input(s)
  - metaphlan_db_latest:
      type: directory
      description: Directory containing uncompressed MetaPhlAn database
  - save_samfile:
      type: boolean
      description: Save SAM output
output:
  - profile:
      type: file
      description: MetaPhlAn profile
      pattern: "*_profile.txt"
  - biom:
      type: file
      description: BIOM profile
      pattern: "*.biom"
  - bt2out:
      type: file
      description: Bowtie2 output
      pattern: "*.bowtie2out.txt"
  - sam:
      type: file
      description: SAM output
      pattern: "*.sam"
  - versions:
      type: file
      description: Versions YAML
      pattern: "versions.yml"
authors:
  - "@nf-core"
