repository_type: pipeline

nf_core_version: 3.5.2

lint: {}

template:
  org: nf-core
  name: rxbiome
  description: Reproducible pipeline for pharmacomicrobiomics
  author: Sanya Badole
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - fastqc
    - gpu
  is_nfcore: true
